config/routes.rb
Blue::Application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  root "companies#index"

  resources :companies do
    resources :members
  end

  resources :events


end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :members

  validates :name, presence: true
  validates :name, length: { in: 1..20 }
  validates :industry, presence: true
  validates :industry, length: { in: 1..20 }
  validates :employee_count, presence: true
  validates :employee_count, numericality: { only_integer: true }
  validates :join_date, presence: { message: "is definitely required."}

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :member
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :company

  validates :name, presence: true
  validates :title, presence: true
  validates :title, length: { in: 1..20 }

  validates :email, presence: true, uniqueness: true, format: { with: /@/ }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :timeoutable
  devise :database_authenticatable, :registerable, :validatable,
         :recoverable, :rememberable, :trackable, :lockable,
         :omniauthable

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.name = auth['info']['name']
      user.email = auth['info']['email']
    end
  end

  def password_required?
    super && provider.blank?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception




  def authorize_admin!
    if current_user.role != "admin"
      flash[:notice] = "You are not authorized to do that!"
      redirect_to :root
    end
  end


end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_company, only: [:edit, :update, :destroy, :show]


  def index
    @companies = Company.all
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)

    if @company.save
      flash[:success] = "Saved company successfully"
      redirect_to :companies
    else
      flash[:alert] = "Failed to save company"
      render :new
    end
  end

  def edit
  end

  def update
    if @company.update(company_params)
      redirect_to :companies
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @company.destroy

    redirect_to :companies
  end

  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company)
          .permit(:name, :industry, :employee_count, :join_date)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_admin!, except: [:index, :show]
  before_action :set_event, only: [:edit, :update, :destroy, :show]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      flash[:success] = "Saved event successfully"
      redirect_to :events
    else
      flash[:alert] = "Failed to save event"
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to :events
    else
      render :edit
    end
  end

  def destroy
    @event.destroy

    redirect_to :events
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event)
          .permit(:title, :description, :capacity, :start_at, :end_at)
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_admin!



  def show
    @member = Member.find(params[:id])
  end

  def new
    @company = Company.find(params[:company_id])
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)
    @company = nil

    if @member.save
      redirect_to company_path(@member.company_id)
    else
      @company = Company.find(@member.company_id)
      render 'new'
    end
  end

  def edit
    @company = Company.find(params[:company_id])
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    @company = nil

    if @member.update(member_params)
      redirect_to company_path(@member.company_id)
    else
      @company = Company.find(@member.company_id)
      render 'edit'
    end

  end

  def destroy
    member = Member.find(params[:id])
    company_id = member.company_id
    member.destroy

    redirect_to company_path(company_id)
  end


  def member_params
    params.require(:member)
          .permit(:name, :title, :email, :company_id)
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def github
    auth = request.env['omniauth.auth']
    user = User.find_by(provider: auth['provider'], uid: auth['uid']) || User.create_with_omniauth(auth)

    if user.persisted?
      flash[:success] = "successfully logged in"
      sign_in_and_redirect user, notice: "signed in"
    else
      redirect_to :root, notice: "failed to persist"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Signed out!'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/companies/_form.html.erb
<ul>
<% @company.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
<% end %>
</ul>


<%= form_for(@company) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>

  <%= f.label :industry %>
  <%= f.select :industry, options_for_select([['Choose...', ''], 'finance', 'tech']) %>
  <br>

  <%= f.label :employee_count %>
  <%= f.text_field :employee_count %>
  <br>

  <%= f.label :join_date %>
  <%= f.date_field :join_date %>
  <br>


  <%= f.submit class: "button radius" %>

<% end %>

app/views/companies/edit.html.erb
<h2>Editing <%= @company.name %></h2>

<%= render 'form' %>

app/views/companies/index.html.erb
<h1>Blue Companies</h1>

<table>
  <thead>
    <tr>
      <td>Name</td>
      <td>Industry</td>
      <td>Employees</td>
      <td>Joined</td>
      <td></td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to company.name, company_path(company) %></td>
        <td><%= company.industry %></td>
        <td><%= company.employee_count %></td>
        <td><%= company.join_date %></td>

        <% if user_signed_in? && current_user.role == "admin" %>
          <td><%= link_to "edit", edit_company_url(company), class: "button tiny round" %></td>
          <td><%= link_to "delete", company, method: :delete, class: "button tiny alert round" %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>



<br>

<%= link_to "Add new", new_company_path, class: "button radius" %>

app/views/companies/new.html.erb
<h2>Add a new company</h2>

<%= render 'form' %>

app/views/companies/show.html.erb
This is the show page

<h3>Company</h3>

<ul>
  <li>Name: <%= @company.name %></li>
  <li>Industry: <%= @company.industry %></li>
  <li>Employees: <%= @company.employee_count %></li>
  <li>Joined: <%= @company.join_date %></li>
</ul>

<hr>
<h3>Members</h3>

<table>
  <thead>
    <tr>
      <td>Name</td>
      <td>Title</td>
      <td>Email</td>
      <td></td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @company.members.each do |member| %>
      <tr>
        <td><%= link_to member.name, company_member_path(@company, member) %></td>
        <td><%= member.title %></td>
        <td><%= member.email %></td>
        <td><%= link_to "edit", edit_company_member_path(@company, member) , class: "button tiny round" %></td>
        <td><%= link_to "delete", company_member_path(@company, member), method: :delete, class: "button tiny alert round" %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<br>

<%= link_to "Add new", new_company_member_path(@company), class: "button radius" %>

app/views/events/_form.html.erb
<ul>
<% @event.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
<% end %>
</ul>


<%= form_for(@event) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>

  <%= f.label :description %>
<<<<<<< Updated upstream
  <%= f.text_area :description %>
  <br>

  <%= f.label :capacity %>
  <%= f.text_field :capacity %>
  <br>

  <%= f.label :start_at %>
  <%= f.date_field :start_at %>
  <br>

  <%= f.label :end_at %>
  <%= f.date_field :end_at %>
=======
  <%= f.text_field :description %>
  <br>

  <%= f.label :start_at %>
  <%= f.date_select :start_at %>
  <br>

  <%= f.label :end_at %>
  <%= f.date_select :end_at %>

  <%= f.label :capacity %>
  <%= f.text_field :capacity %>
>>>>>>> Stashed changes
  <br>

  <%= f.submit class: "button radius" %>

<% end %>

app/views/events/edit.html.erb
<h2>Edit Event</h2>

<%= render 'form' %>

app/views/events/index.html.erb
<h2>All Events</h2>

<table>
  <thead>
    <tr>
      <td>Title</td>
      <td>Description</td>
      <td>Capacity</td>
      <td>Start</td>
      <td>End</td>
      <td></td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.title, event_path(event) %></td>
        <td><%= event.description %></td>
        <td><%= event.capacity %></td>
        <td><%= event.start_at %></td>
        <td><%= event.end_at %></td>
        <td><%= link_to "edit", edit_event_url(event), class: "button tiny round" %></td>
        <td><%= link_to "delete", event, method: :delete, class: "button tiny alert round" %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<br>

<%= link_to "Add new", new_event_path, class: "button radius" %>

app/views/events/new.html.erb
<h2>New Event</h2>

<%= render 'form' %>

app/views/events/show.html.erb
<h2>Event</h2>

<ul>
  <li>Title: <%= @event.title %></li>
  <li>Description: <%= @event.description %></li>
  <li>Capacity: <%= @event.capacity %></li>
  <li>Start: <%= @event.start_at %></li>
  <li>End: <%= @event.end_at %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title>Blue</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="row">
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Blue Directory</a></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Left Nav Section -->
      <ul class="left">
        <li><%= link_to "companies", companies_path %></li>
        <li><%= link_to "events", events_path %></li>
      </ul>

    <ul class="right">
      <% if user_signed_in? %>
      <li><a href="#">Hi, <%= current_user.email %>!</a></li>
      <li class="has-dropdown">
        <a href="#">Account</a>
        <ul class="dropdown">
          <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>

      <% else %>
      <li class="has-dropdown">
        <a href="#">Account</a>
        <ul class="dropdown">
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Signin w/github", user_omniauth_authorize_path(:github) %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        </ul>
      <% end %>
      </li>
    </ul>

    </section>
  </nav>
</div>


<div class="row">
  <div>
  <% flash.each do |key, value| %>
    <div class="alert-box <%= key %>"><%= value %></div>
  <% end %>
  </div>
</div>

<div class="row">
  <%= yield %>
</div>



<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>

app/views/members/_form.html.erb
<ul>
<% @member.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
<% end %>
</ul>

<%= form_for(  [@company, @member]) do |f| %>

  Company: <%= @company.name %>
  <br>

  <input type="hidden" name="member[company_id]" value="<%= @company.id %>" />

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>

  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>

  <%= f.submit %>

<% end %>

app/views/members/edit.html.erb
<h2>Edit Member</h2>

<%= render 'form' %>

app/views/members/new.html.erb
<h2>Creating new member</h2>

<%= render 'form' %>

app/views/members/show.html.erb
<h2>Showing member</h2>

Name: <%= @member.name %><br>
Title: <%= @member.title %>